"""ティッカー -> 企業ドメインの対応表。

Clearbit Logo API(https://logo.clearbit.com/<domain>)でロゴを取得するために使う。
時価総額上位の主要銘柄を中心に用意。ここに無い銘柄はロゴをスキップ(テキストのみ)。

新しい銘柄を足したいときはこの辞書に "TICKER": "domain.com" を追記するだけ。
"""

TICKER_DOMAINS = {
    "AAPL": "apple.com",
    "MSFT": "microsoft.com",
    "NVDA": "nvidia.com",
    "AMZN": "amazon.com",
    "GOOGL": "google.com",
    "GOOG": "google.com",
    "META": "meta.com",
    "BRK-B": "berkshirehathaway.com",
    "LLY": "lilly.com",
    "AVGO": "broadcom.com",
    "TSLA": "tesla.com",
    "JPM": "jpmorganchase.com",
    "WMT": "walmart.com",
    "V": "visa.com",
    "XOM": "exxonmobil.com",
    "UNH": "unitedhealthgroup.com",
    "MA": "mastercard.com",
    "PG": "pg.com",
    "JNJ": "jnj.com",
    "HD": "homedepot.com",
    "COST": "costco.com",
    "ORCL": "oracle.com",
    "ABBV": "abbvie.com",
    "BAC": "bankofamerica.com",
    "KO": "coca-cola.com",
    "MRK": "merck.com",
    "CVX": "chevron.com",
    "NFLX": "netflix.com",
    "AMD": "amd.com",
    "PEP": "pepsico.com",
    "CRM": "salesforce.com",
    "TMO": "thermofisher.com",
    "ADBE": "adobe.com",
    "LIN": "linde.com",
    "MCD": "mcdonalds.com",
    "WFC": "wellsfargo.com",
    "CSCO": "cisco.com",
    "ACN": "accenture.com",
    "ABT": "abbott.com",
    "DHR": "danaher.com",
    "INTC": "intel.com",
    "IBM": "ibm.com",
    "QCOM": "qualcomm.com",
    "TXN": "ti.com",
    "GE": "ge.com",
    "VZ": "verizon.com",
    "DIS": "disney.com",
    "PM": "pmi.com",
    "NOW": "servicenow.com",
    "CAT": "caterpillar.com",
    "AMGN": "amgen.com",
    "PFE": "pfizer.com",
    "T": "att.com",
    "INTU": "intuit.com",
    "SPGI": "spglobal.com",
    "GS": "goldmansachs.com",
    "ISRG": "intuitive.com",
    "UBER": "uber.com",
    "BKNG": "booking.com",
    "AXP": "americanexpress.com",
    "MS": "morganstanley.com",
    "RTX": "rtx.com",
    "NKE": "nike.com",
    "HON": "honeywell.com",
    "BA": "boeing.com",
    "SBUX": "starbucks.com",
    "PYPL": "paypal.com",
    "BLK": "blackrock.com",
    "C": "citigroup.com",
    "ADP": "adp.com",
    "GILD": "gilead.com",
    "MDT": "medtronic.com",
    "LMT": "lockheedmartin.com",
}
